services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - path: ./drizzle.config.ts
          target: /drizzle.config.ts
          action: sync+restart
        - path: ./package.json
          target: /package.json
          action: sync+restart
        - path: ./next.config.ts
          target: /next.config.ts
          action: sync+restart
        - path: ./tsconfig.json
          target: /tsconfig.json
          action: sync+restart
        # NOTE: NextJS supports hot reloading for the src directory!
        - path: ./src
          target: /src
          action: sync
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/qa-use
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - qause-network

  postgres:
    restart: always
    image: postgres:15
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qa-use
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    command: postgres -c max_connections=1000
    networks:
      - qause-network

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: pnpm drizzle-kit migrate
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/qa-use
    depends_on:
      postgres:
        condition: service_healthy

    restart: on-failure
    networks:
      - qause-network

networks:
  qause-network:
    driver: bridge
